project:
  type: website

execute:
  freeze: auto

website:
  description: "A blog built with Quarto"
  site-url: https://codedwithpride.github.io # you must change this appropriately for RSS feeds to work properly
  title: "CodedWithPride"
  navbar:
    right:
      - posts.qmd
      - badges.qmd
      - communities.qmd
      - resources.qmd
      - people.qmd
      - about.qmd
      - icon: github
        href: https://github.com/CodedWithPride
format:
  html:
    theme: 
      light: assets/custom_light.scss
      dark: assets/custom_dark.scss




