---
title: Communities
toc: true
---

This page contains some brief information about some of the LGBTQIA+ communities in tech. 

::: {.callout-note}
This is a work-in-progress!

If you know of a community that should be listed here,
please open an issue or pull request on the [website repo](https://github.com/CodedWithPride/codedwithpride.github.io).
:::

## Community spaces

| Group | Website | Description |
| ----------- | ----------- | ----------- |
| LGBTQ in Technology | <https://lgbtq.technology> | The LGBTQ in Technology Slack is a space for LGBTQ people in technology to chat and support each other. |
| Queer Code | <https://queer-code.org> | We are a community of queer coders. We build tech together, share our ideas at local meetups, and provide support for queer people working in software development. |
| QueerJS | <https://queerjs.com> | QueerJS is a meetup series where everyone is encouraged to attend and support the speakers and the idea. |
| rainbowR | <https://rainbowr.org> | Our mission is to connect, support and promote LGBTQ+ people in the R community and to spread awareness of LGBTQ+ issues through data-driven activism |

## Advocacy and visibility and more formal organisations

| Group | Website | Description |
| ----------- | ----------- | ----------- |
| Pride in Stem | <https://prideinstem.org> | Pride in STEM is a charity run by an independent group of LGBTQIA+ scientists & engineers from around the world. Proud of who we are and what we do. We aim to showcase and support all LGBTQIA+ people in STEM fields. |
| TransTech | <https://transtechsocial.org> | TransTech is an incubator for LGBTQ Talent with a focus on economically empowering the T, transgender people, in our community. TransTech is a co-working, co-learning community dedicated to empowering trans, lesbian, gay, bisexual, queer people and allies with practical, career-ready skills. |

## Academics groups

| Group | Website | Description |
| ----------- | ----------- | ----------- |
| 500 Queer Scientists | <https://500queerscientists.com> | A visibility campaign for LGBTQ+ people and their allies working in STEM and STEM-supporting jobs |
| ALDER Network | <https://www.britishecologicalsociety.org/content/join-the-alder-network> | A network for the LGBTQIA+ ecologist community to interact, share and support each other. |
| NYU Queer Data Lab | <https://wp.nyu.edu/queer_data_lab> | Queering and Elevating Empirical Research through Data |
| Out to Innovate | <https://www.outtoinnovate.org/home> | Out to Innovate is a professional society and global community of LGBTQ+ students and professionals in science, technology, engineering, and mathematics. |
| Queer, Equality and Diversity (QED) Network for Maths | <https://sites.google.com/view/qednetwork/home> | The QED network is a community-led effort by queer mathematical staff (including PhD students) to connect and support LGBTQIA+ members of the UK mathematics community. |
| Spectra | <https://www.lgbtmath.org> | The Association for LGBT Mathematicians |
